apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: myapp
    tier: db
spec:
  containers:
  - name: postgres
    image: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: mysecretpassword